workflows:
  shikhaya-android:
    name: Shikhaya Android Build

    environment:
      flutter: stable

    scripts:
      - name: Unzip source
        script: |
          unzip -o shikhaya_app_source.zip

      - name: Create Android project
        script: |
          cd shikhaya
          flutter create . --platforms=android

      - name: Firebase options
        script: |
          cd shikhaya
          echo "firebase_options.dart already exists"

      - name: Install packages
        script: |
          cd shikhaya
          flutter pub get

      - name: Build APK
        script: |
          cd shikhaya
          flutter build apk --release

    artifacts:
      - shikhaya/build/**/outputs/**/*.apk
